# Generated by Django 5.0.1 on 2026-01-21 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='StreamingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('ms_played', models.IntegerField()),
                ('conn_country', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_addr_decrypted', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_decrypted', models.TextField(blank=True, null=True)),
                ('master_metadata_track_name', models.CharField(blank=True, max_length=500, null=True)),
                ('master_metadata_album_artist_name', models.CharField(blank=True, max_length=500, null=True)),
                ('master_metadata_album_album_name', models.CharField(blank=True, max_length=500, null=True)),
                ('spotify_track_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_name', models.CharField(blank=True, max_length=500, null=True)),
                ('episode_show_name', models.CharField(blank=True, max_length=500, null=True)),
                ('spotify_episode_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_start', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_end', models.CharField(blank=True, max_length=100, null=True)),
                ('shuffle', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('offline_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('incognito_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='data_upload.spotifydataupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['user', 'ts'], name='data_upload_user_id_dcfc6d_idx'), models.Index(fields=['master_metadata_track_name'], name='data_upload_master__696fa7_idx')],
            },
        ),
    ]
