# Generated by Django 5.0.1 on 2026-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaminghistory',
            name='incognito_mode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='streaminghistory',
            name='offline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='streaminghistory',
            name='shuffle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='streaminghistory',
            name='skipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
